const SHOW_LOADER = "SHOW_LOADER";
const HIDE_LOADER = "HIDE_LOADER";
const RECEIVE_MENU_DATA = "RECEIVE_MENU_DATA";
const SEARCH_MENU_DISHES = "SEARCH_MENU_DISHES";
const SELECT_MENU_ITEM = "SELECT_MENU_ITEM";
const FETCH_SELECTED_DISHES = "FETCH_SELECTED_DISHES";
const RESET_STATE = "RESET_STATE";

export {
  SHOW_LOADER,
  HIDE_LOADER,
  RECEIVE_MENU_DATA,
  SEARCH_MENU_DISHES,
  SELECT_MENU_ITEM,
  FETCH_SELECTED_DISHES,
  RESET_STATE,
};
